### ISSUE TITLE
No DragEnd Event dispatched

### ISSUE THREAD

**Issue by MartinMuzatko** [BMSVieira/letmescroll.js#2]
![image](https://user-images.githubusercontent.com/2950505/152166426-78df1e8f-9066-4ce8-937f-a47567421765.png)

As you can see, I actually never retrieve a `dragEnd` event

**Comment by BMSVieira** [comment]
Hey, thank you for this issue.
This is for sure a bug in chromium engine browsers, it has already been fixed.

It will be out in the next commit, thanks.

**Comment by BMSVieira** [comment]
Fixed with the last commit, thanks!
