### ISSUE TITLE
No click on track allowed

### ISSUE THREAD

**Issue by MartinMuzatko** [BMSVieira/letmescroll.js#3]
Hello! Usually when I click on the track in the scrollbar, I am able to navigate to the direction I have clicked. This makes interaction more accessible. This could be configurable if needed.

**Comment by BMSVieira** [comment]
Thats something it will be added for sure, thank you!

**Comment by BMSVieira** [comment]
Hey, this feature was added in the previous commit, check it out.

Thank you!
