### ISSUE TITLE
Not enough content error

### ISSUE THREAD

**Issue by harryheman** [BMSVieira/letmescroll.js#4]
Hello, my friend. Great tool, but when actual height of scrolling container > config.dimensions.height (when we have little content) , we get `TypeError: Cannot set properties of undefined (setting 'opacity')` from this code:
```js
var hideElement = this.hideElement = function hideElement(element, value) {
    element.style.opacity = value;
}
```

**Comment by BMSVieira** [comment]
Hello, 
Yes, it is a bug.. it will be fixed very soon in the next commit. 

Thank you!

**Comment by BMSVieira** [comment]
Fixed in the last commit, thank you for reporting.
