### ISSUE TITLE
Scrollbar is sometimes there and someties its gone. 

### ISSUE THREAD

**Issue by Mohika** [BMSVieira/letmescroll.js#5]
Very weird! When I just resize the browser window it shows.   autoHide: false

**Comment by BMSVieira** [comment]
Hello Mohika,

Can you please tell me more information about this "bug"? 

How can i replicate it?
What browser were you using?

Thank you!

**Comment by Mohika** [comment]
The browser is Chrome same happens in Edge, haven't tested other browsers. I have just removed the script. 

The environment is WordPress and WP Bakery Visual Composer and Gantry 5 framework. Checked if the caching plugin has something to do with it and it doesn't as It happens if not cached. The console is not showing any error. 

I guess I will just need to style the sidebar with the CSS.

**Comment by Mohika** [comment]
Here is the script I used

```
<script>


document.addEventListener("DOMContentLoaded", function() {
    demo1 = new LetMeScroll({
     selector: "#side-news",
     config : {
           dimensions : {
               width : "41.66666667%",
               height : "485px"
           },
           scroll : {
             bottomOffset: 0,
             autoHide: false
           }
     }
   });    
   

   
   demo2 = new LetMeScroll({
     selector: "#side-events",
     config : {
           dimensions : {
               width : "41.66666667%",
               height : "485px"
           },
           scroll : {
             bottomOffset: 0,
             autoHide: false
           }
     }
   });
   

});


</script>
```

**Comment by Mohika** [comment]
Tried with jQuery ready function as well ... no difference ...

**Comment by Mohika** [comment]
My need was limited only to the custom design of it .. so this worked for me ... 

`/* Custom Scrolbar */

/* width */
  ::-webkit-scrollbar {
  width: 25px;
  border-radius: 5px;
}

/* Track */
 ::-webkit-scrollbar-track {
  background: #fff;
  border: 1px solid #eee;
}
 
/* Handle */
::-webkit-scrollbar-thumb {
	background: #E6E7E8;
	border: 5px solid transparent;
    border-radius: 10px;
    background-clip: content-box;
}

/* Handle on hover */
 ::-webkit-scrollbar-thumb:hover {
    background: #aaa;
  	border: 5px solid transparent;
    border-radius: 10px;
    background-clip: content-box;
}
`
