### ISSUE TITLE
Where I can find the 'config' options?

### ISSUE THREAD

**Issue by wittywolk** [BMSVieira/letmescroll.js#7]
Hi,
where I can find the 'config' options? Because based on my testings scrollbar can work without putting dimensions into config but it won't work without 'scroll : (...)'. Where I can find the list of parameters? And the ones that are needed and not needed?

**Comment by wittywolk** [comment]
Unfortunately the scroll doesn't seem to update on it's own in my project when content is added so I have to use other script, kinda sad but I don't have time to troubleshoot that. Other than that great script.

**Comment by BMSVieira** [comment]
hey, 

It's wierd because the scroll should update whenever you are using the appendTo() method.
But since it doesn't, you can use the refresh() method.

**Comment by BMSVieira** [comment]
> Hi, where I can find the 'config' options? Because based on my testings scrollbar can work without putting dimensions into config but it won't work without 'scroll : (...)'. Where I can find the list of parameters? And the ones that are needed and not needed?

So, i updated the code and fixed a little bug where it assumes the default configs when you do not provide any configuration.
From now on, the only required option is the "selector", other than that... it will assume the default values wich are:

```javascript
const defaults = {
    selector : 'given ID', <-- Required 
    config : {
        dimensions : {
            width : "100%",
            height : "500px"
        },
        scroll : {
            bottomOffset: 0,
            autoHide: false
        }
    },
    onComplete: function(){},
    onEnd: function(){},
    onTop: function(){},
    onMove: function(){},
    onDragStart: function(){},
    onDragStop: function(){},
    onTouchStart: function(){},
    onTouchStop: function(){}
};   
```

**Comment by wittywolk** [comment]
> hey,
> 
> It's wierd because the scroll should update whenever you are using the appendTo() method. But since it doesn't, you can use the refresh() method.

I'm not using this method, sorry, I'm not great at JS. You made good working script but unfortunately not for my usecase. 
https://flyingatom.com/testowanie/scroll/ - here, I setup a demo with your script and MiniBar. 
You can see what I mean by checking 'Kantor' checkbox and then scroll - you will see that your scrollbar stops at like 75% even though it is the end of the box.
